// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtE3JHWQFqvHGCkoMc4aivEeGOv-FAeFw',
    appId: '1:10788095280:web:0bbac6c4c913b74993f4f5',
    messagingSenderId: '10788095280',
    projectId: 'namer-app-kitbees',
    authDomain: 'namer-app-kitbees.firebaseapp.com',
    storageBucket: 'namer-app-kitbees.firebasestorage.app',
    measurementId: 'G-S2CQQX93G1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTMu9b-e5T2c1uNFt6KzFh6hW-t1DHLkA',
    appId: '1:718875273858:android:5069fee28ae9fdf754a29b',
    messagingSenderId: '718875273858',
    projectId: 'namer-project-50f7d',
    storageBucket: 'namer-project-50f7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmZEpUCSIiETpyYSPEpUKGrTxV3yG0zXE',
    appId: '1:10788095280:ios:f6bee1214686469f93f4f5',
    messagingSenderId: '10788095280',
    projectId: 'namer-app-kitbees',
    storageBucket: 'namer-app-kitbees.firebasestorage.app',
    iosBundleId: 'com.example.namerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmZEpUCSIiETpyYSPEpUKGrTxV3yG0zXE',
    appId: '1:10788095280:ios:f6bee1214686469f93f4f5',
    messagingSenderId: '10788095280',
    projectId: 'namer-app-kitbees',
    storageBucket: 'namer-app-kitbees.firebasestorage.app',
    iosBundleId: 'com.example.namerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtE3JHWQFqvHGCkoMc4aivEeGOv-FAeFw',
    appId: '1:10788095280:web:b41d209d0671e6a493f4f5',
    messagingSenderId: '10788095280',
    projectId: 'namer-app-kitbees',
    authDomain: 'namer-app-kitbees.firebaseapp.com',
    storageBucket: 'namer-app-kitbees.firebasestorage.app',
    measurementId: 'G-RTC30CRERL',
  );
}
